config:
  experiment_name: "real_building"
  block: "output_block_4","output_block_5","output_block_6","" # the module name of the visualized features (e.g. "output_block_4", "input_block_7").
  experiments_fit: # the list of the experiments to visualize the features for
    - "RS"
  experiments_transform: # the list of the experiments used for calculating the principal components
    - "RS"
