source_experiment_name: "RS" # the experiment name of the source image
prompts: # text prompts for translations
  - "a photo of buildings at autumn in remote sensing image"
  - "a photo of buildings covered by snow in remote sensing image"

scale: 7.5 # unconditional guidance scale. Note that a higher value encourages deviation from the source image
num_ddim_sampling_steps: 50 # if left empty, defaults to the ddim_steps_callback arg used in the source experiment

# Control the level of structure preservation with injection timestep threshold
feature_injection_threshold: 30 # should be in [0, num_ddim_sampling_steps],injection when t>threshold

# Control the level of deviation from the source image with Negative prompting params.
negative_prompt: 
negative_prompt_alpha: 1.0 # ∈ [0, 1], determines the initial strength of negative-prompting (lower = stronger)
negative_prompt_schedule: "linear" # ∈ {"linear", "constant", "exp"}, determines the attenuation schedule of negative-prompting
# setting negative_prompt_alpha = 1.0, negative_prompt_schedule = "constant" is equivalent to not using negative prompting
